"""tablas iniciales

Revision ID: d3cb5ce265bc
Revises: 
Create Date: 2026-02-10 09:35:03.974420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cb5ce265bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienteproveedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nit', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('lote', sa.String(length=12), nullable=False),
    sa.Column('invima', sa.String(length=15), nullable=True),
    sa.Column('valor', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=2, scale=2), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.String(length=150), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos')
    op.drop_table('insumos')
    op.drop_table('clienteproveedor')
    # ### end Alembic commands ###
